### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by XiaoJiNu** [jeya-maria-jose/KiU-Net-pytorch#1]
Hi, when I trained the model with custom data,  it always told that CUDA out of memory. I tried resize image to 608x608 and use bath size 1 but can't solve the problem. What's wrong?

**Comment by jeya-maria-jose** [comment]
@XiaoJiNu  So, this code works perfectly with image size as 128*128 using any GeForce version GPU with batch size 1. You can do either of the two things: 1) resize the image to 128*128 or somewhere closer to that resolution. 2) Reduce the number of layers and filters in the network by modifying the code such that you can accommodate 608*608.
