### ISSUE TITLE
Memmory usage of kiunet3d

### ISSUE THREAD

**Issue by olyaee** [jeya-maria-jose/KiU-Net-pytorch#12]
Hi, 
Could you please give some information about GPU memory is needed for kiunet3d? I couldn't train it on a GeForce gtx 1080 with 11 GB of memory.

**Comment by jeya-maria-jose** [comment]
Hi, if you are using brats dataset , kiunet 3d should work in a 11 GB memory GPU if you set n=6. In case you are using the LiTS dataset, please consider using the  kiunet_min model found in LiTS folder in case you have a 11GB memory.
