### ISSUE TITLE
`t >= 0 && t < n_classes` failed. RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by jiangjiaxi20** [jeya-maria-jose/KiU-Net-pytorch#13]
when run the train.py, got this bug

**Comment by jeya-maria-jose** [comment]
This bug occurs when the ground truth masks have more classes than the number of classes in prediction. Please make sure you ground truth images have only 0 or 1 labels of pixels if you are training for binary segmentation. The datasets usually have the ground truth as 0 or 255 labels of pixels. So, please convert them to 0's and 1's.
