### ISSUE TITLE
Own dataset

### ISSUE THREAD

**Issue by iratxeMoya** [jeya-maria-jose/KiU-Net-pytorch#15]
Hi,

I would like to use my own dataset and train the model, but I don know how to create it. Should I label my 3D images? If so, how can I do it? Is there any software like labelme for 2D images?

Sorry for the inconveniences

**Comment by jeya-maria-jose** [comment]
Hi, 

You can check out ITK-SNAP in case if you look forward to make annotations for 3D medical images.
