### ISSUE TITLE
did you resize all the data into128*128? train with 128*128, test with 128*128, including all the labels?? 

### ISSUE THREAD

**Issue by jiangjiaxi20** [jeya-maria-jose/KiU-Net-pytorch#16]

**Comment by jeya-maria-jose** [comment]
Yes, for the 2D experiments all the images were resized to 128*128. I am also planning to upload the folders containing the resized images for all the experiments soon !

**Comment by jeya-maria-jose** [comment]
@jiangjiaxi20 I have uploaded the resized version of the dataset. Hope it helps !
