### ISSUE TITLE
where i can find the dataset in your paper?

### ISSUE THREAD

**Issue by lmmcc** [jeya-maria-jose/KiU-Net-pytorch#2]
I want to reproduce your paper result.but have no dataset just mentioned in your paper.so can u share the dataset.

**Comment by jeya-maria-jose** [comment]
@lmmcc You can search for the public datasets that we compared in the appendix of the arXiv paper to reproduce the results. I am afraid the US data used for experiments in the main paper cannot be made public atleast for now

**Comment by lmmcc** [comment]
> @lmmcc You can search for the public datasets that we compared in the appendix of the arXiv paper to reproduce the results. I am afraid the US data used for experiments in the main paper cannot be made public atleast for now

ok,thanks!
