### ISSUE TITLE
About the preprocessing data?

### ISSUE THREAD

**Issue by hwx10** [jeya-maria-jose/KiU-Net-pytorch#24]
Hi!
Follow the code, the train data should be png. I want to run the 2D model.
But I could not find the code to convert nii to png. 
The preprocess workflow: First, run  LiTs/data_prepare/get_training_set.py; second, convert nii to png. Is it right?
And could you share the code(second step)  with me? 
Thank you!
![QQ图片20210423150341](https://user-images.githubusercontent.com/57698625/115832365-68083880-a445-11eb-88c7-02e1042de2cf.png)

**Comment by jeya-maria-jose** [comment]
Hi, 

This format is meant for training 2D images. To run the LiTS experiment, please follow these [instructions](https://github.com/jeya-maria-jose/KiU-Net-pytorch/blob/master/LiTS/README.md).

**Comment by hwx10** [comment]
> Hi,
> 
> This format is meant for training 2D images. To run the LiTS experiment, please follow these [instructions](https://github.com/jeya-maria-jose/KiU-Net-pytorch/blob/master/LiTS/README.md).

Thanks for your reply. 
The another question is: when wil be the Brain Anatomy US dataset  public? 
I wanna apply  kiunet for 2D medical dataset.
Thanks!

**Comment by jeya-maria-jose** [comment]
Hopefully by next month ! Thanks for your interest !

**Comment by DanpengDing** [comment]
> Hi,
> 
> This format is meant for training 2D images. To run the LiTS experiment, please follow these [instructions](https://github.com/jeya-maria-jose/KiU-Net-pytorch/blob/master/LiTS/README.md).

can you share code nii to png？and LITS image size is 128*128？
