### ISSUE TITLE
cudnn_status_mapping error

### ISSUE THREAD

**Issue by lmmcc** [jeya-maria-jose/KiU-Net-pytorch#3]
when I run your code with my own data. I encounter this problem"CUDNN_STATUS_MAPPING_ERROR"，my pytorch version is 1.5,cuda 10.2. not the same as yours.

**Comment by jeya-maria-jose** [comment]
https://github.com/pytorch/pytorch/issues/33134

I think it is due to the mismatch between your GPU and pytorch&CUDA version. Your GPU might not be compatible with the latest pytorch version. Please downgrade CUDA and pytorch according to your GPU edition.
