### ISSUE TITLE
i trained the model for 100 epoch, but the pred.nii seems only recongnize the liver. would you please give some trained weights file(.pth) of the LiTS? 

### ISSUE THREAD

**Issue by jiangjiaxi20** [jeya-maria-jose/KiU-Net-pytorch#8]

**Comment by jeya-maria-jose** [comment]
For this work , we only perform experiments on Task 1 (Liver Segmentation) of the Lits dataset and not perform Task 2 (Liver tumor segmentation of the lits dataset. So, pred.nii recongnizing only the liver is not wrong. Yes, I will upload the pre-trained weights soon.
